
server:
  port: 2333
  servlet:
    context-path: "/ms01"

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ms01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#  type-aliases-package: com.tsu.ms00.bean
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true

file:
  staticAccessPath: /img/**
  uploadLocation: C:\code\mslyp\files\